sudo: required

language: node_js

node_js:
- 6.0.0

branches:
  only:
  - dev

before_install:
- openssl aes-256-cbc -K $encrypted_eab4b037e21f_key -iv $encrypted_eab4b037e21f_iv
  -in github-ci.enc -out ~/.ssh/id_rsa -d
- chmod 0600 ~/.ssh/id_rsa
- cp ssh_config ~/.ssh/config
- sudo cp ssh_config /etc/ssh/ssh_config
- sudo chmod 755 /etc/ssh/ssh_config
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/id_rsa
- git config --global user.name "huixisheng"
- git config --global user.email "469184346@qq.com"
- npm install -g hexo-cli

install:
- npm install

script:
- hexo clean
- hexo generate
- hexo deploy

after_success:
- hexo deploy

addons:
  ssh_known_hosts
  - github.com
  - ssh.github.com
